spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/nookatkg
    username: root
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
  jackson:
    date-format: yyyy-MM-dd
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1034168671711-1am50g05qkp50ikretudc5pjfl06hffj.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1247490096006769
            client-secret: ca612dd4b418e6df8609ab3ebcd4e689
server:
  port: 8000
